# Generated by Django 2.2 on 2020-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('description', models.TextField(default='', null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('dislikes', models.IntegerField(default=0, null=True)),
                ('comments', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True, null=True)),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('token', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
