# Generated by Django 2.2 on 2020-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='comments',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
