# Generated by Django 2.2 on 2020-08-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20200823_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
